# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant::Config.run do |config|
	config.vm.box = "lucid32"
	config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
	config.vm.forward_port 3306, 3306
	config.vm.forward_port 5672, 5672
	config.vm.network :hostonly, "192.168.56.2"
	config.vm.provision :shell, :path => "setup.sh"
end